//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayerBDSmartVideo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=E:\Dropbox\B3\C#\SmartVideo\Web@SmartVideo\App_Data\aspnet-Web_SmartVideo-c2f8567b-990f-42f9-a084-cb2f2fe2e2be.mdf;Initial Catalog=aspnet-Web_SmartVideo-c2f8567b-990f-42f9-a084-cb2f2fe2e2be;Integrated Security=True")]
        public string aspnet_Web_SmartVideo_c2f8567b_990f_42f9_a084_cb2f2fe2e2beConnectionString {
            get {
                return ((string)(this["aspnet_Web_SmartVideo_c2f8567b_990f_42f9_a084_cb2f2fe2e2beConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=BDSmartVideo;Integrated Securi" +
            "ty=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True")]
        public string BDSmartVideoConnectionString {
            get {
                return ((string)(this["BDSmartVideoConnectionString"]));
            }
        }
    }
}
