<?xml version="1.0" encoding="utf-8"?><Database Name="BDSmartVideo" Class="BDSmartVideoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=BDSmartVideo;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="DataAccessLayerBDSmartVideo.Properties.Settings" SettingsPropertyName="BDSmartVideoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Client" Member="Client">
    <Type Name="Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Prenom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Adresse" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Client_Location" Member="Location" ThisKey="Id" OtherKey="IdClient" Type="Location" />
      <Association Name="Client_Hits" Member="Hits" ThisKey="Id" OtherKey="IdClient" Type="Hits" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Location">
    <Type Name="Location">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdFilm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdClient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateDebut" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DateFin" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Client_Location" Member="Client" ThisKey="IdClient" OtherKey="Id" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hits" Member="Hits">
    <Type Name="Hits">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdClient" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Critere" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Hits" Member="Client" ThisKey="IdClient" OtherKey="Id" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
</Database>